#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sassc
Version  : 3.5.0
Release  : 1
URL      : https://github.com/sass/sassc/archive/3.5.0.tar.gz
Source0  : https://github.com/sass/sassc/archive/3.5.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: sassc-bin
BuildRequires : libsass
BuildRequires : libsass-dev

%description
SassC
=======
[![Unix CI](https://secure.travis-ci.org/sass/sassc.svg?branch=master)](http://travis-ci.org/sass/sassc)
[![Windows CI](https://ci.appveyor.com/api/projects/status/github/sass/sassc?svg=true)](https://ci.appveyor.com/project/sass/sassc/branch/master)

%package bin
Summary: bin components for the sassc package.
Group: Binaries

%description bin
bin components for the sassc package.


%prep
%setup -q -n sassc-3.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522196259
%reconfigure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1522196259
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sassc
